version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management
      && rabbitmq-server"

